# Generated by Django 4.1.2 on 2022-10-17 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="user",
            new_name="critic",
        ),
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Ensure this value is greater than or equal to 1."
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Ensure this value is less than or equal to 10."
                    ),
                ]
            ),
        ),
    ]
